version: '3.8'

services:
  web:
    build: .
    ports:
      - "${LOCAL_PORT}:5000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - OPENROUTER_MODEL=${OPENROUTER_MODEL}
      - WA_SENDER_API_URL=${WA_SENDER_API_URL}
      - WA_SENDER_API_KEY=${WA_SENDER_API_KEY}
      - WA_SENDER_WEBHOOK_SECRET=${WA_SENDER_WEBHOOK_SECRET}
    depends_on:
      - db
    command: gunicorn --bind 0.0.0.0:5000 --timeout 300 --workers ${WORKERS} app:app
    restart: unless-stopped

  db:
    image: ankane/pgvector
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data: